### ISSUE TITLE
Non-deterministic test failure on a GPU system

### ISSUE THREAD

**Issue by lcw** [exanauts/ExaPF.jl#137] opened 2021-03-27 01:31 UTC
With the changes in https://github.com/exanauts/ExaPF.jl/pull/136 I was able to
successfully run the tests on my local computer using CUDA.jl.  However, one
time a test failed (see transcript below).  At first glance I didn't see any
non-determinism in the test so I wonder if the failure is related to issue
https://github.com/exanauts/ExaPF.jl/issues/110 where other non-deterministic
behaviour is described.

```
❯ julia --project=.                                        
               _                                           
   _       _ _(_)_     |  Documentation: https://docs.julialang.org                                                    
  (_)     | (_) (_)    |                                   
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.                                                        
  | | | | | | |/ _` |  |                                   
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)       
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release                                                      
|__/                   |                                   

julia> versioninfo()                                       
Julia Version 1.6.0                                        
Commit f9720dc2eb (2021-03-24 12:55 UTC)                   
Platform Info:                                             
  OS: Linux (x86_64-pc-linux-gnu)                          
  CPU: AMD Ryzen 7 2700X Eight-Core Processor              
  WORD_SIZE: 64                                            
  LIBM: libopenlibm                                        
  LLVM: libLLVM-11.0.1 (ORCJIT, znver1)                    
Environment:                                               
  JULIA_MPI_BINARY = system                                

julia> using CUDA

julia> CUDA.versioninfo()
CUDA toolkit 11.0.3, artifact installation
CUDA driver 11.0.0
NVIDIA driver 450.102.4

Libraries: 
- CUBLAS: 11.2.0
- CURAND: 10.2.1
- CUFFT: 10.2.1
- CUSOLVER: 10.6.0
- CUSPARSE: 11.1.1
- CUPTI: 13.0.0
- NVML: 11.0.0+450.102.4
- CUDNN: 8.10.0 (for CUDA 11.2.0)
- CUTENSOR: 1.2.2 (for CUDA 11.1.0)

Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: GeForce RTX 2060 (sm_75, 4.622 GiB / 5.792 GiB available)

(ExaPF) pkg> test                                          
     Testing ExaPF                                         
      Status `/tmp/jl_8ipLGV/Project.toml`                 
  [6e4b80f9] BenchmarkTools v0.5.0                         
  [052768ef] CUDA v2.6.2                                   
  [0cf0e50c] ExaPF v0.4.0 `~/research/code/ExaPF.jl`       
  [6a86dc24] FiniteDiff v2.8.0                             
  [f6369f11] ForwardDiff v0.10.17                          
  [b6b21f68] Ipopt v0.6.5                                  
  [42fd0dbc] IterativeSolvers v0.8.5                       
  [63c18a36] KernelAbstractions v0.4.6                     
  [ba0b0d4f] Krylov v0.5.5                                 
  [093fc24a] LightGraphs v1.3.5                            
  [b8f27783] MathOptInterface v0.9.20                      
  [2679e427] Metis v1.0.0                                  
  [47a9eef4] SparseDiffTools v1.13.0                       
  [a759f4b9] TimerOutputs v0.5.8                           
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`         
  [de0858da] Printf `@stdlib/Printf`                       
  [9a3f8284] Random `@stdlib/Random`                       
  [2f01184e] SparseArrays `@stdlib/SparseArrays`           
  [8dfed614] Test `@stdlib/Test`                           
      Status `/tmp/jl_8ipLGV/Manifest.toml`                
  [621f4979] AbstractFFTs v1.0.1                           
  [79e6a3ab] Adapt v3.2.0                                  
  [ec485272] ArnoldiMethod v0.1.0                          
  [4fba245c] ArrayInterface v3.1.6                         
  [ab4f0b2a] BFloat16s v0.1.0                              
  [6e4b80f9] BenchmarkTools v0.5.0                         
  [b99e7846] BinaryProvider v0.5.10                        
  [fa961155] CEnum v0.4.1                                  
  [052768ef] CUDA v2.6.2                                   
  [7057c7e9] Cassette v0.3.5                               
  [d360d2e6] ChainRulesCore v0.9.33                        
  [523fee87] CodecBzip2 v0.7.2                             
  [944b1d66] CodecZlib v0.7.0                              
  [bbf7d656] CommonSubexpressions v0.3.0                   
  [34da2185] Compat v3.25.0                                
  [864edb3b] DataStructures v0.18.9                        
  [163ba53b] DiffResults v1.0.3                            
  [b552c78f] DiffRules v1.0.2                              
  [0cf0e50c] ExaPF v0.4.0 `~/research/code/ExaPF.jl`       
  [e2ba6199] ExprTools v0.1.3                              
  [9aa1b823] FastClosures v0.3.2                           
  [6a86dc24] FiniteDiff v2.8.0                             
  [f6369f11] ForwardDiff v0.10.17                          
  [0c68f7d7] GPUArrays v6.2.0                              
  [61eb1bfa] GPUCompiler v0.10.0                           
  [cd3eb016] HTTP v0.9.5                                   
  [615f187c] IfElse v0.1.0                                 
  [d25df0c9] Inflate v0.1.2                                
  [83e8ac13] IniFile v0.5.0                                
  [b6b21f68] Ipopt v0.6.5                                  
  [42fd0dbc] IterativeSolvers v0.8.5                       
  [692b3bcd] JLLWrappers v1.2.0                            
  [682c06a0] JSON v0.21.1                                  
  [7d188eb4] JSONSchema v0.3.3                             
  [63c18a36] KernelAbstractions v0.4.6                     
  [ba0b0d4f] Krylov v0.5.5                                 
  [929cbde3] LLVM v3.6.0                                   
  [093fc24a] LightGraphs v1.3.5                            
  [5c8ed15e] LinearOperators v1.1.0                        
  [1914dd2f] MacroTools v0.5.6                             
  [b8f27783] MathOptInterface v0.9.20                      
  [fdba3010] MathProgBase v0.7.8                           
  [739be429] MbedTLS v1.0.3                                
  [c03570c3] Memoize v0.4.4                                
  [2679e427] Metis v1.0.0                                  
  [d8a4904e] MutableArithmetics v0.2.14                    
  [872c559c] NNlib v0.7.17                                 
  [77ba4419] NaNMath v0.3.5                                
  [bac558e1] OrderedCollections v1.4.0                     
  [69de0a69] Parsers v1.1.0                                
  [3cdcf5f2] RecipesBase v1.1.1                            
  [189a3867] Reexport v1.0.0                               
  [ae029012] Requires v1.1.3                               
  [6c6a2e73] Scratch v1.0.3                                
  [699a6c99] SimpleTraits v0.9.3                           
  [47a9eef4] SparseDiffTools v1.13.0                       
  [276daf66] SpecialFunctions v1.3.0                       
  [aedffcd0] Static v0.2.4                                 
  [90137ffa] StaticArrays v1.0.1                           
  [a759f4b9] TimerOutputs v0.5.8                           
  [3bb67fe8] TranscodingStreams v0.9.5                     
  [5c2747f8] URIs v1.2.0                                   
  [19fa3120] VertexSafeGraphs v0.1.2                       
  [a5390f91] ZipFile v0.9.3                                
  [ae81ac8f] ASL_jll v0.1.1+4                              
  [6e34b625] Bzip2_jll v1.0.6+5                            
  [9cc047cb] Ipopt_jll v3.13.4+0                           
  [d00139f3] METIS_jll v5.1.0+5                            
  [d7ed1dd3] MUMPS_seq_jll v5.2.1+4                        
  [656ef2d0] OpenBLAS32_jll v0.3.12+1                      
  [efe28fd5] OpenSpecFun_jll v0.5.3+4                      
  [0dad84c5] ArgTools `@stdlib/ArgTools`                   
  [56f22d72] Artifacts `@stdlib/Artifacts`                 
  [2a0f44e3] Base64 `@stdlib/Base64`                       
  [ade2ca70] Dates `@stdlib/Dates`                         
  [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`       
  [8ba89e20] Distributed `@stdlib/Distributed`             
  [f43a241f] Downloads `@stdlib/Downloads`                 
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`   
  [4af54fe1] LazyArtifacts `@stdlib/LazyArtifacts`         
  [b27032c2] LibCURL `@stdlib/LibCURL`                     
  [76f85450] LibGit2 `@stdlib/LibGit2`                     
  [8f399da3] Libdl `@stdlib/Libdl`                         
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`         
  [56ddb016] Logging `@stdlib/Logging`                     
  [d6f4376e] Markdown `@stdlib/Markdown`                   
  [a63ad114] Mmap `@stdlib/Mmap`                           
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`       
  [44cfe95a] Pkg `@stdlib/Pkg`                             
  [de0858da] Printf `@stdlib/Printf`                       
  [3fa0cd96] REPL `@stdlib/REPL`                           
  [9a3f8284] Random `@stdlib/Random`                       
  [ea8e919c] SHA `@stdlib/SHA`                             
  [9e88b42a] Serialization `@stdlib/Serialization`         
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`           
  [6462fe0b] Sockets `@stdlib/Sockets`                     
  [2f01184e] SparseArrays `@stdlib/SparseArrays`           
  [10745b16] Statistics `@stdlib/Statistics`               
  [fa267f1f] TOML `@stdlib/TOML`                           
  [a4e569a6] Tar `@stdlib/Tar`                             
  [8dfed614] Test `@stdlib/Test`                           
  [cf7118a7] UUIDs `@stdlib/UUIDs`                         
  [4ec0a83e] Unicode `@stdlib/Unicode`                     
  [e66e0078] CompilerSupportLibraries_jll `@stdlib/CompilerSupportLibraries_jll`                                       
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`             
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`             
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`             
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`                                                           
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`                   
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`             
  [3f19e933] p7zip_jll `@stdlib/p7zip_jll`                 
  Progress [========================================>]  22/22                                                          
22 dependencies successfully precompiled in 42 seconds (53 already precompiled)                                        
     Testing Running tests...                              
Reading PSSE format                                        
┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`                                                                                                      
└ @ GPUArrays ~/.julia/packages/GPUArrays/WV76E/src/host/indexing.jl:43                                                
Test Summary:        | Pass  Total                         
Problem formulations |   85     85                         
Test Summary:     | Pass  Total                            
Iterative solvers |   36     36                            
Reading PSSE format                                        
┌ Warning: PowerSystem: cost is not specified in PowerNetwork dataset                                                  
└ @ ExaPF.PowerSystem ~/research/code/ExaPF.jl/src/PowerSystem/power_network.jl:211                                    
┌ Warning: PowerSystem: cost is not specified in PowerNetwork dataset                                                  
└ @ ExaPF.PowerSystem ~/research/code/ExaPF.jl/src/PowerSystem/power_network.jl:211                                    
┌ Warning: Newton-Raphson algorithm failed to converge (182.29864183960703)                                            
└ @ ExaPF ~/research/code/ExaPF.jl/src/Evaluators/reduced_evaluator.jl:105                                             
Test API on CUDADevice(): Test Failed at /home/lucas/research/code/ExaPF.jl/test/reduced_evaluator.jl:65               
  Expression: isapprox(grad_fd, g, rtol = 0.0001)          
   Evaluated: isapprox([-9.935589542501313, 83.29418125602783, 176.58606788964127, 0.0, 88.79764713761492, 61.87925810156231, 5.407209203348859, -16.0610823203679, 21.697626222124487, -5.750990592075815, -11.972362422178843], [-9.935589556165517, 83.29418101143494, 176.5860680653392, 54.61617710821696, 88.79764714293702, 61.87925824943278, 5.407209536445407, -16.061082207200116, 21.697626170063813, -5.75099045219747, -11.97236266954647]; rtol = 0.0001)                      
Stacktrace:                                                
 [1] macro expansion                                       
   @ ~/research/code/ExaPF.jl/test/reduced_evaluator.jl:65 [inlined]                                                   
 [2] macro expansion                                       
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1226 [inlined]             
 [3] macro expansion                                       
   @ ~/research/code/ExaPF.jl/test/reduced_evaluator.jl:22 [inlined]                                                   
 [4] top-level scope                                       
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1226                       
┌ Warning: Passing optimizer attributes as keyword arguments to                                                        
│ `Ipopt.Optimizer` is deprecated. Use                     
│     MOI.set(model, MOI.RawParameter("key"), value)       
│ or                                                       
│     JuMP.set_optimizer_attribute(model, "key", value)    
│ instead.                                                 
└ @ Ipopt ~/.julia/packages/Ipopt/P1XLY/src/MOI_wrapper.jl:88                                                          

******************************************************************************                                         
This program contains Ipopt, a library for large-scale nonlinear optimization.                                         
 Ipopt is released as open source code under the Eclipse Public License (EPL).                                         
         For more information visit https://github.com/coin-or/Ipopt                                                   
******************************************************************************                                         

Test Summary:                       | Pass  Fail  Total    
Optimization evaluators             |  192     1    193    
  Powerflow solver                  |   36           36    
  Compute reduced gradient on CPU   |    8            8    
  ReducedSpaceEvaluators (case9.m)  |   62           62    
  ReducedSpaceEvaluators (case30.m) |   61     1     62    
    Constructor                     |   10           10    
    Constructor                     |   10           10    
    Test API on CPU()               |   21           21    
    Test API on CUDADevice()        |   20     1     21    
  PenaltyEvaluators                 |   10           10    
  AugLagEvaluators                  |   13           13    
  MOI wrapper                       |    2            2    
ERROR: LoadError: Some tests did not pass: 192 passed, 1 failed, 0 errored, 0 broken.                                  
in expression starting at /home/lucas/research/code/ExaPF.jl/test/runtests.jl:29                                       
ERROR: Package ExaPF errored during testing                

(ExaPF) pkg> test                                          
     Testing ExaPF                                         
      Status `/tmp/jl_xEjmzT/Project.toml`                 
  [6e4b80f9] BenchmarkTools v0.5.0                         
  [052768ef] CUDA v2.6.2                                   
  [0cf0e50c] ExaPF v0.4.0 `~/research/code/ExaPF.jl`       
  [6a86dc24] FiniteDiff v2.8.0                             
  [f6369f11] ForwardDiff v0.10.17                          
  [b6b21f68] Ipopt v0.6.5                                  
  [42fd0dbc] IterativeSolvers v0.8.5                       
  [63c18a36] KernelAbstractions v0.4.6                     
  [ba0b0d4f] Krylov v0.5.5                                 
  [093fc24a] LightGraphs v1.3.5                            
  [b8f27783] MathOptInterface v0.9.20                      
  [2679e427] Metis v1.0.0                                  
  [47a9eef4] SparseDiffTools v1.13.0                       
  [a759f4b9] TimerOutputs v0.5.8                           
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`         
  [de0858da] Printf `@stdlib/Printf`                       
  [9a3f8284] Random `@stdlib/Random`                       
  [2f01184e] SparseArrays `@stdlib/SparseArrays`           
  [8dfed614] Test `@stdlib/Test`                           
      Status `/tmp/jl_xEjmzT/Manifest.toml`                
  [621f4979] AbstractFFTs v1.0.1                           
  [79e6a3ab] Adapt v3.2.0                                  
  [ec485272] ArnoldiMethod v0.1.0                          
  [4fba245c] ArrayInterface v3.1.6                         
  [ab4f0b2a] BFloat16s v0.1.0                              
  [6e4b80f9] BenchmarkTools v0.5.0                         
  [b99e7846] BinaryProvider v0.5.10                        
  [fa961155] CEnum v0.4.1                                  
  [052768ef] CUDA v2.6.2                                   
  [7057c7e9] Cassette v0.3.5                               
  [d360d2e6] ChainRulesCore v0.9.33                        
  [523fee87] CodecBzip2 v0.7.2                             
  [944b1d66] CodecZlib v0.7.0                              
  [bbf7d656] CommonSubexpressions v0.3.0                   
  [34da2185] Compat v3.25.0                                
  [864edb3b] DataStructures v0.18.9                        
  [163ba53b] DiffResults v1.0.3                            
  [b552c78f] DiffRules v1.0.2                              
  [0cf0e50c] ExaPF v0.4.0 `~/research/code/ExaPF.jl`       
  [e2ba6199] ExprTools v0.1.3                              
  [9aa1b823] FastClosures v0.3.2                           
  [6a86dc24] FiniteDiff v2.8.0                             
  [f6369f11] ForwardDiff v0.10.17                          
  [0c68f7d7] GPUArrays v6.2.0                              
  [61eb1bfa] GPUCompiler v0.10.0                           
  [cd3eb016] HTTP v0.9.5                                   
  [615f187c] IfElse v0.1.0                                 
  [d25df0c9] Inflate v0.1.2                                
  [83e8ac13] IniFile v0.5.0                                
  [b6b21f68] Ipopt v0.6.5                                  
  [42fd0dbc] IterativeSolvers v0.8.5                       
  [692b3bcd] JLLWrappers v1.2.0                            
  [682c06a0] JSON v0.21.1                                  
  [7d188eb4] JSONSchema v0.3.3                             
  [63c18a36] KernelAbstractions v0.4.6                     
  [ba0b0d4f] Krylov v0.5.5                                 
  [929cbde3] LLVM v3.6.0                                   
  [093fc24a] LightGraphs v1.3.5                            
  [5c8ed15e] LinearOperators v1.1.0                        
  [1914dd2f] MacroTools v0.5.6                             
  [b8f27783] MathOptInterface v0.9.20                      
  [fdba3010] MathProgBase v0.7.8                           
  [739be429] MbedTLS v1.0.3                                
  [c03570c3] Memoize v0.4.4                                
  [2679e427] Metis v1.0.0                                  
  [d8a4904e] MutableArithmetics v0.2.14                    
  [872c559c] NNlib v0.7.17                                 
  [77ba4419] NaNMath v0.3.5                                
  [bac558e1] OrderedCollections v1.4.0                     
  [69de0a69] Parsers v1.1.0                                
  [3cdcf5f2] RecipesBase v1.1.1                            
  [189a3867] Reexport v1.0.0                               
  [ae029012] Requires v1.1.3                               
  [6c6a2e73] Scratch v1.0.3                                
  [699a6c99] SimpleTraits v0.9.3                           
  [47a9eef4] SparseDiffTools v1.13.0                       
  [276daf66] SpecialFunctions v1.3.0                       
  [aedffcd0] Static v0.2.4                                 
  [90137ffa] StaticArrays v1.0.1                           
  [a759f4b9] TimerOutputs v0.5.8                           
  [3bb67fe8] TranscodingStreams v0.9.5                     
  [5c2747f8] URIs v1.2.0                                   
  [19fa3120] VertexSafeGraphs v0.1.2                       
  [a5390f91] ZipFile v0.9.3                                
  [ae81ac8f] ASL_jll v0.1.1+4                              
  [6e34b625] Bzip2_jll v1.0.6+5                            
  [9cc047cb] Ipopt_jll v3.13.4+0                           
  [d00139f3] METIS_jll v5.1.0+5                            
  [d7ed1dd3] MUMPS_seq_jll v5.2.1+4                        
  [656ef2d0] OpenBLAS32_jll v0.3.12+1                      
  [efe28fd5] OpenSpecFun_jll v0.5.3+4                      
  [0dad84c5] ArgTools `@stdlib/ArgTools`                   
  [56f22d72] Artifacts `@stdlib/Artifacts`                 
  [2a0f44e3] Base64 `@stdlib/Base64`                       
  [ade2ca70] Dates `@stdlib/Dates`                         
  [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`       
  [8ba89e20] Distributed `@stdlib/Distributed`             
  [f43a241f] Downloads `@stdlib/Downloads`                 
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`   
  [4af54fe1] LazyArtifacts `@stdlib/LazyArtifacts`         
  [b27032c2] LibCURL `@stdlib/LibCURL`                     
  [76f85450] LibGit2 `@stdlib/LibGit2`                     
  [8f399da3] Libdl `@stdlib/Libdl`                         
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`         
  [56ddb016] Logging `@stdlib/Logging`                     
  [d6f4376e] Markdown `@stdlib/Markdown`                   
  [a63ad114] Mmap `@stdlib/Mmap`                           
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`       
  [44cfe95a] Pkg `@stdlib/Pkg`                             
  [de0858da] Printf `@stdlib/Printf`                       
  [3fa0cd96] REPL `@stdlib/REPL`                           
  [9a3f8284] Random `@stdlib/Random`                       
  [ea8e919c] SHA `@stdlib/SHA`                             
  [9e88b42a] Serialization `@stdlib/Serialization`         
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`           
  [6462fe0b] Sockets `@stdlib/Sockets`                     
  [2f01184e] SparseArrays `@stdlib/SparseArrays`           
  [10745b16] Statistics `@stdlib/Statistics`               
  [fa267f1f] TOML `@stdlib/TOML`                           
  [a4e569a6] Tar `@stdlib/Tar`                             
  [8dfed614] Test `@stdlib/Test`                           
  [cf7118a7] UUIDs `@stdlib/UUIDs`                         
  [4ec0a83e] Unicode `@stdlib/Unicode`                     
  [e66e0078] CompilerSupportLibraries_jll `@stdlib/CompilerSupportLibraries_jll`                                       
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`             
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`             
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`             
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`                                                           
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`                   
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`             
  [3f19e933] p7zip_jll `@stdlib/p7zip_jll`                 
     Testing Running tests...                              
Reading PSSE format                                        
┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`                                                                                                      
└ @ GPUArrays ~/.julia/packages/GPUArrays/WV76E/src/host/indexing.jl:43                                                
Test Summary:        | Pass  Total                         
Problem formulations |   85     85                         
Test Summary:     | Pass  Total                            
Iterative solvers |   36     36                            
Reading PSSE format                                        
┌ Warning: PowerSystem: cost is not specified in PowerNetwork dataset                                                  
└ @ ExaPF.PowerSystem ~/research/code/ExaPF.jl/src/PowerSystem/power_network.jl:211                                    
┌ Warning: PowerSystem: cost is not specified in PowerNetwork dataset                                                  
└ @ ExaPF.PowerSystem ~/research/code/ExaPF.jl/src/PowerSystem/power_network.jl:211                                    
┌ Warning: Passing optimizer attributes as keyword arguments to                                                        
│ `Ipopt.Optimizer` is deprecated. Use                     
│     MOI.set(model, MOI.RawParameter("key"), value)       
│ or                                                       
│     JuMP.set_optimizer_attribute(model, "key", value)    
│ instead.                                                 
└ @ Ipopt ~/.julia/packages/Ipopt/P1XLY/src/MOI_wrapper.jl:88                                                          

******************************************************************************                                         
This program contains Ipopt, a library for large-scale nonlinear optimization.                                         
 Ipopt is released as open source code under the Eclipse Public License (EPL).                                         
         For more information visit https://github.com/coin-or/Ipopt                                                   
******************************************************************************                                         

Test Summary:           | Pass  Total                      
Optimization evaluators |  193    193                      
Test Summary:            | Pass  Total                     
Reduced space algorithms |    2      2                     
     Testing ExaPF tests passed                            

(ExaPF) pkg> test                                          
     Testing ExaPF                                         
      Status `/tmp/jl_rbh8TS/Project.toml`                 
  [6e4b80f9] BenchmarkTools v0.5.0                         
  [052768ef] CUDA v2.6.2                                   
  [0cf0e50c] ExaPF v0.4.0 `~/research/code/ExaPF.jl`       
  [6a86dc24] FiniteDiff v2.8.0                             
  [f6369f11] ForwardDiff v0.10.17                          
  [b6b21f68] Ipopt v0.6.5                                  
  [42fd0dbc] IterativeSolvers v0.8.5                       
  [63c18a36] KernelAbstractions v0.4.6                     
  [ba0b0d4f] Krylov v0.5.5                                 
  [093fc24a] LightGraphs v1.3.5                            
  [b8f27783] MathOptInterface v0.9.20                      
  [2679e427] Metis v1.0.0                                  
  [47a9eef4] SparseDiffTools v1.13.0                       
  [a759f4b9] TimerOutputs v0.5.8                           
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`         
  [de0858da] Printf `@stdlib/Printf`                       
  [9a3f8284] Random `@stdlib/Random`                       
  [2f01184e] SparseArrays `@stdlib/SparseArrays`           
  [8dfed614] Test `@stdlib/Test`                           
      Status `/tmp/jl_rbh8TS/Manifest.toml`                
  [621f4979] AbstractFFTs v1.0.1                           
  [79e6a3ab] Adapt v3.2.0                                  
  [ec485272] ArnoldiMethod v0.1.0                          
  [4fba245c] ArrayInterface v3.1.6                         
  [ab4f0b2a] BFloat16s v0.1.0                              
  [6e4b80f9] BenchmarkTools v0.5.0                         
  [b99e7846] BinaryProvider v0.5.10                        
  [fa961155] CEnum v0.4.1                                  
  [052768ef] CUDA v2.6.2                                   
  [7057c7e9] Cassette v0.3.5                               
  [d360d2e6] ChainRulesCore v0.9.33                        
  [523fee87] CodecBzip2 v0.7.2                             
  [944b1d66] CodecZlib v0.7.0                              
  [bbf7d656] CommonSubexpressions v0.3.0                   
  [34da2185] Compat v3.25.0                                
  [864edb3b] DataStructures v0.18.9                        
  [163ba53b] DiffResults v1.0.3                            
  [b552c78f] DiffRules v1.0.2                              
  [0cf0e50c] ExaPF v0.4.0 `~/research/code/ExaPF.jl`       
  [e2ba6199] ExprTools v0.1.3                              
  [9aa1b823] FastClosures v0.3.2                           
  [6a86dc24] FiniteDiff v2.8.0                             
  [f6369f11] ForwardDiff v0.10.17                          
  [0c68f7d7] GPUArrays v6.2.0                              
  [61eb1bfa] GPUCompiler v0.10.0                           
  [cd3eb016] HTTP v0.9.5                                   
  [615f187c] IfElse v0.1.0                                 
  [d25df0c9] Inflate v0.1.2                                
  [83e8ac13] IniFile v0.5.0                                
  [b6b21f68] Ipopt v0.6.5                                  
  [42fd0dbc] IterativeSolvers v0.8.5                       
  [692b3bcd] JLLWrappers v1.2.0                            
  [682c06a0] JSON v0.21.1                                  
  [7d188eb4] JSONSchema v0.3.3                             
  [63c18a36] KernelAbstractions v0.4.6                     
  [ba0b0d4f] Krylov v0.5.5                                 
  [929cbde3] LLVM v3.6.0                                   
  [093fc24a] LightGraphs v1.3.5                            
  [5c8ed15e] LinearOperators v1.1.0                        
  [1914dd2f] MacroTools v0.5.6                             
  [b8f27783] MathOptInterface v0.9.20                      
  [fdba3010] MathProgBase v0.7.8                           
  [739be429] MbedTLS v1.0.3                                
  [c03570c3] Memoize v0.4.4                                
  [2679e427] Metis v1.0.0                                  
  [d8a4904e] MutableArithmetics v0.2.14                    
  [872c559c] NNlib v0.7.17                                 
  [77ba4419] NaNMath v0.3.5                                
  [bac558e1] OrderedCollections v1.4.0                     
  [69de0a69] Parsers v1.1.0                                
  [3cdcf5f2] RecipesBase v1.1.1                            
  [189a3867] Reexport v1.0.0                               
  [ae029012] Requires v1.1.3                               
  [6c6a2e73] Scratch v1.0.3                                
  [699a6c99] SimpleTraits v0.9.3                           
  [47a9eef4] SparseDiffTools v1.13.0                       
  [276daf66] SpecialFunctions v1.3.0                       
  [aedffcd0] Static v0.2.4                                 
  [90137ffa] StaticArrays v1.0.1                           
  [a759f4b9] TimerOutputs v0.5.8                           
  [3bb67fe8] TranscodingStreams v0.9.5                     
  [5c2747f8] URIs v1.2.0                                   
  [19fa3120] VertexSafeGraphs v0.1.2                       
  [a5390f91] ZipFile v0.9.3                                
  [ae81ac8f] ASL_jll v0.1.1+4                              
  [6e34b625] Bzip2_jll v1.0.6+5                            
  [9cc047cb] Ipopt_jll v3.13.4+0                           
  [d00139f3] METIS_jll v5.1.0+5                            
  [d7ed1dd3] MUMPS_seq_jll v5.2.1+4                        
  [656ef2d0] OpenBLAS32_jll v0.3.12+1                      
  [efe28fd5] OpenSpecFun_jll v0.5.3+4                      
  [0dad84c5] ArgTools `@stdlib/ArgTools`                   
  [56f22d72] Artifacts `@stdlib/Artifacts`                 
  [2a0f44e3] Base64 `@stdlib/Base64`                       
  [ade2ca70] Dates `@stdlib/Dates`                         
  [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`       
  [8ba89e20] Distributed `@stdlib/Distributed`             
  [f43a241f] Downloads `@stdlib/Downloads`                 
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`   
  [4af54fe1] LazyArtifacts `@stdlib/LazyArtifacts`         
  [b27032c2] LibCURL `@stdlib/LibCURL`                     
  [76f85450] LibGit2 `@stdlib/LibGit2`                     
  [8f399da3] Libdl `@stdlib/Libdl`                         
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`         
  [56ddb016] Logging `@stdlib/Logging`                     
  [d6f4376e] Markdown `@stdlib/Markdown`                   
  [a63ad114] Mmap `@stdlib/Mmap`                           
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`       
  [44cfe95a] Pkg `@stdlib/Pkg`                             
  [de0858da] Printf `@stdlib/Printf`                       
  [3fa0cd96] REPL `@stdlib/REPL`                           
  [9a3f8284] Random `@stdlib/Random`                       
  [ea8e919c] SHA `@stdlib/SHA`                             
  [9e88b42a] Serialization `@stdlib/Serialization`         
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`           
  [6462fe0b] Sockets `@stdlib/Sockets`                     
  [2f01184e] SparseArrays `@stdlib/SparseArrays`           
  [10745b16] Statistics `@stdlib/Statistics`               
  [fa267f1f] TOML `@stdlib/TOML`                           
  [a4e569a6] Tar `@stdlib/Tar`                             
  [8dfed614] Test `@stdlib/Test`                           
  [cf7118a7] UUIDs `@stdlib/UUIDs`                         
  [4ec0a83e] Unicode `@stdlib/Unicode`                     
  [e66e0078] CompilerSupportLibraries_jll `@stdlib/CompilerSupportLibraries_jll`                                       
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`             
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`             
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`             
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`                                                           
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`                   
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`             
  [3f19e933] p7zip_jll `@stdlib/p7zip_jll`                 
     Testing Running tests...                              
Reading PSSE format                                        
┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`                                                                                                      
└ @ GPUArrays ~/.julia/packages/GPUArrays/WV76E/src/host/indexing.jl:43                                                
Test Summary:        | Pass  Total                         
Problem formulations |   85     85                         
Test Summary:     | Pass  Total                            
Iterative solvers |   36     36                            
Reading PSSE format                                        
┌ Warning: PowerSystem: cost is not specified in PowerNetwork dataset                                                  
└ @ ExaPF.PowerSystem ~/research/code/ExaPF.jl/src/PowerSystem/power_network.jl:211                                    
┌ Warning: PowerSystem: cost is not specified in PowerNetwork dataset                                                  
└ @ ExaPF.PowerSystem ~/research/code/ExaPF.jl/src/PowerSystem/power_network.jl:211                                    
┌ Warning: Passing optimizer attributes as keyword arguments to                                                        
│ `Ipopt.Optimizer` is deprecated. Use                     
│     MOI.set(model, MOI.RawParameter("key"), value)       
│ or                                                       
│     JuMP.set_optimizer_attribute(model, "key", value)    
│ instead.                                                 
└ @ Ipopt ~/.julia/packages/Ipopt/P1XLY/src/MOI_wrapper.jl:88                                                          

******************************************************************************                                         
This program contains Ipopt, a library for large-scale nonlinear optimization.                                         
 Ipopt is released as open source code under the Eclipse Public License (EPL).                                         
         For more information visit https://github.com/coin-or/Ipopt                                                   
******************************************************************************                                         

Test Summary:           | Pass  Total                      
Optimization evaluators |  193    193                      
Test Summary:            | Pass  Total                     
Reduced space algorithms |    2      2                     
     Testing ExaPF tests passed                            

(ExaPF) pkg>                                               
```

**Comment by michel2323** [comment] 2021-03-27 03:00
@lcw Yes. This looks like #110 . We are still looking into that. We do have the issue in another code unrelated to `ExaPF` when using the CUSPARSE API of CUDA.jl. But it's too early to draw conclusions.

**Comment by michel2323** [comment] 2021-03-29 16:27
Duplicate of #110 .

**Closed by michel2323** 2021-03-29 16:27 UTC
Labels: duplicate
